services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: Zaq12wsx

  db:
    image: postgres:alpine
    container_name: fastapi-postgres
    restart: always
    environment:
      POSTGRES_DB: fastapi_database
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: Zaq12wsx
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
      - /usr/src/app/node_modules/
    ports:
      - 4200:4200
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    depends_on:
      - backend

volumes:
  postgres_data:


