services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_NAME=online_shop
      - DB_USER=root
      - DB_PASSWORD=Zaq12wsx
      - DB_PORT=3306

  
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Zaq12wsx
      MYSQL_DATABASE: online_shop
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: